config/routes.rb
Rails.application.routes.draw do
post ':user_name/follow_user', to: 'relationships#follow_user',
as: :follow_user
post ':user_name/unfollow_user', to:
'relationships#unfollow_user', as: :unfollow_user


  # get 'notifications/link_through'
  get 'notifications/:id/link_through', to:'notifications#link_through',as: :link_through

  get 'notifications', to: 'notifications#index'

  get 'profiles/show'
  get 'browse', to: 'posts#browse', as: :browse_posts


  # devise_for :users
  devise_for :users, :controllers => { registrations:
'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :posts

resources :posts do
resources :comments
member do
get 'like'
get 'unlike'
end
end


  root 'posts#index'
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as:
  :update_profile



end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]

  def show
    # @user = User.find_by(user_name: params[:user_name])

    @posts = User.find_by(user_name:
                          params[:user_name]).posts.order('created_at DESC')
  end

  def edit
    # @user = User.find_by(user_name: params[:user_name])
  end

  def update
    @user = User.find_by(user_name: params[:user_name])
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private
  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
    # @user = User.find_by(user_name: params[:user_name])
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end







end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: {multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4> Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user)%>
                </div>
                <%= f.file_field :avatar, onChange:'loadFile(event)'%>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4> Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 ,style:"width:90%";%>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_for @user, url: {action: "update"}, html: {multipart: true } do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your profile image:
                .img-circle
                  = profile_avatar_select(@user)
                = f.file_field :avatar, onChange:'loadFile(event)'
          .row
            .col-md-12
              .form-group.text-center
                %h4 Update your bio:
                = f.text_area :bio, label: false, rows: 4 ,style:"width:90%";
          .form-group.text-center
            = f.submit "Update Profile", class: 'btn btn-success'

app/views/profiles/follow_user.js.erb
$('#follow-button').attr('class', 'btn unfollow-button').text('Following').attr('href', "/<%= @user.user_name%>/unfollow_user").attr('id', 'unfollow-button')

app/views/profiles/show.html.erb
<div class="row profile-header" style="background: rgba(158,158,158,0.06);">
  <div class="col-md-6">
    <div class="img-circle">
      <%= profile_avatar_select(@user)%>
    </div>
  </div>
  <div class="col-md-6">
    <div class="user-name-and-follow">
      <h3 class="profile-user-name">
        <%= @user.user_name%>
      </h3>
      <span>
        <% if @user == current_user %>
          <%= link_to 'Edit Profile',edit_profile_path(@user.user_name),class: 'btn edit-button'%>
        <%else%>
          <% if !current_user.following(@user.id).empty?%>
            <%= link_to 'Following', unfollow_user_path, remote: true,class: 'btn unfollow-button',id: 'unfollow-button',method: :post%>
          <%else%>
            <%= link_to 'Follow', follow_user_path, remote: true,class: 'btn follow-button',id: 'follow-button',method: :post%>
          <%end%>
        <%end%>
      </span>
    </div>
    <p class="profile-bio">
      <%= @user.bio%>
    </p>
    <div class="row user-statistics">
      <p class="col-md-4">
        <%= pluralize @user.posts.count, 'post'%>
      </p>
      <p class="col-md-4">
        <%= pluralize @user.followers.count, 'follower'%>
      </p>
      <p class="col-md-4">
        <%= pluralize @user.following.count, 'following'%>
      </p>
    </div>
  </div>
</div>
<div class="posts-wrapper">
  <% @posts.each do |post|%>
    <%= render 'posts/post', post: post%>
  <%end%>
</div>

app/views/profiles/unfollow_user.js.erb
$('#unfollow-button').text('Follow').attr('class', 'btn follow-button').attr('href', "/<%= @user.user_name%>/follow_user").attr('id', 'follow-button');