config/routes.rb
Rails.application.routes.draw do
post ':user_name/follow_user', to: 'relationships#follow_user',
as: :follow_user
post ':user_name/unfollow_user', to:
'relationships#unfollow_user', as: :unfollow_user


  # get 'notifications/link_through'
  get 'notifications/:id/link_through', to:'notifications#link_through',as: :link_through

  get 'notifications', to: 'notifications#index'

  get 'profiles/show'
  get 'browse', to: 'posts#browse', as: :browse_posts


  # devise_for :users
  devise_for :users, :controllers => { registrations:
'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :posts

resources :posts do
resources :comments
member do
get 'like'
get 'unlike'
end
end


  root 'posts#index'
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as:
  :update_profile



end

app/models/notification.rb
class Notification < ApplicationRecord
  validates :user_id, :notified_by_id, :post_id, :identifier,
  :notice_type, presence: true

  belongs_to :notified_by, class_name: 'User'
  belongs_to :user
  belongs_to :subscribed_user
  belongs_to :post
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.notifications

  end

  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to post_path @notification.post
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li>
<%= link_to "#{notification.notified_by.user_name} has #{notification.notice_type}ed on your post",link_through_path(notification)%>
</li>

app/views/notifications/_notificiation_dropdown.html.erb
<div class="dropdown notification-dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
<%= current_user.notifications.count %>
</button>
<span class="glyphicon glyphicon-flag"></span>
<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
<li class="dropdown-header text-center">Notifications</li>
<%= render current_user.notifications.order('created_at DESC').last(5) %>
<li class="divider" role="separator">
<li class="text-center">
  <%= link_to 'View All', notifications_path %>
</li>
</li>
</ul>


</div>

app/views/notifications/index.html.erb
<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-0">
<ul class="notification-index-list">
<%= render @notifications %>
</ul>
</div>
</div>
</div>

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>