config/routes.rb
Rails.application.routes.draw do
post ':user_name/follow_user', to: 'relationships#follow_user',
as: :follow_user
post ':user_name/unfollow_user', to:
'relationships#unfollow_user', as: :unfollow_user


  # get 'notifications/link_through'
  get 'notifications/:id/link_through', to:'notifications#link_through',as: :link_through

  get 'notifications', to: 'notifications#index'

  get 'profiles/show'
  get 'browse', to: 'posts#browse', as: :browse_posts


  # devise_for :users
  devise_for :users, :controllers => { registrations:
'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :posts

resources :posts do
resources :comments
member do
get 'like'
get 'unlike'
end
end


  root 'posts#index'
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as:
  :update_profile



end

app/models/post.rb
class Post < ApplicationRecord
has_many :notifications, dependent: :destroy

acts_as_votable
belongs_to :user
has_many :comments, dependent: :destroy
validates :user_id, presence: true
validates :image, presence: true
validates :caption, length: { minimum: 3, maximum: 300 }
has_attached_file :image, styles: { :medium => "640x" },
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml")
validates_attachment_content_type :image, :content_type =>
/\Aimage\/.*\Z/


scope :of_followed_users, -> (following_users) { where user_id:
following_users }


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy,
                                  :like,:unlike]
  before_action :owned_post, only: [:edit, :update, :destroy]


  def index
    @posts =
    Post.of_followed_users(current_user.following).order('created_at
         DESC').page params[:page]
  end


  def new
    # @post = Post.new
    @post=current_user.posts.build
  end

  def create
    # if @post = Post.create(post_params)
    # flash[:success] = "Your post has been created!"
    # redirect_to posts_path
    # else
    # flash.now[:alert] = "Your new post couldn't be created!
    # Please check the form."
    # render :new
    # end
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash[:alert] = "Your new post couldn't be created!
Please check the form."
      render :new
    end

  end

  def show
    # @post = Post.find(params[:id])
  end

  def edit
    # @post = Post.find(params[:id])
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed.
form."
      render :edit
    end
  end

  def destroy
    # @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end


  def like
    if @post.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unlike
    if @post.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def browse
    @posts = Post.all.order('created_at DESC').page params[:page]
  end





  private
  def post_params
    params.require(:post).permit(:image,:caption)
  end
  def set_post
    @post = Post.find(params[:id])
  end
  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end



end

app/helpers/posts_helper.rb
module PostsHelper

def likers_of(post)
votes = post.votes_for.up.by_type(User)
user_names = []
unless votes.blank?
votes.voters.each do |voter|
user_names.push(link_to voter.user_name,
profile_path(voter.user_name),
class: 'user-name')
end
user_names.to_sentence.html_safe + like_plural(votes)
end
end

def display_likes(post)
votes = post.votes_for.up.by_type(User)
return list_likers(votes) if votes.size <= 8
count_likers(votes)
end

def liked_post(post)
return 'glyphicon-heart' if current_user.voted_for? post
'glyphicon-heart-empty'
end

def like_unlike(post)
	return "/posts/#{post.id}/unlike" if current_user.voted_for? post
		"/posts/#{post.id}/like"
end

private
def list_likers(votes)
user_names = []
unless votes.blank?
votes.voters.each do |voter|
user_names.push(link_to voter.user_name,
profile_path(voter.user_name),
class: 'user-name')
end
user_names.to_sentence.html_safe + like_plural(votes)
end
end
def count_likers(votes)
vote_count = votes.size
vote_count.to_s + ' likes'
end


def like_plural(votes)
return ' like this' if votes.count > 1
' likes this'
end

end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_image_select(@post) %>
        <%= simple_form_for @post, html: {multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
            <%if  f.error_notification%>
              <%= f.error_notification %>
              <%end%>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4> Upload an image (this is required):</h4>
              <%= f.input :image, label: false, input_html: {onChange: 'loadFile(event)' } %>
            </div>
            <div class="form-group text-center">
              <%= f.input :caption ,label: false,placeholder:'Add your caption',:input_html => { :class => 'form-control' }%>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn-success btn-block' %>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>
<!-- <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form> -->

app/views/posts/_likes.html.erb
<!-- <div class="likes">
<%= likers_of post %>
</div> -->
<div class="likes" id="likes_<%= post.id %>">
<%= display_likes post%>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper row">
</div>
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name"><%= link_to post.user.user_name,profile_path(post.user.user_name)%>
      </div>
      <div class="time-ago">
        <%= time_ago_in_words post.created_at%>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)%>
    </div>
    <div class="post-bottom">
      <%= render 'posts/likes', post: post %>
      <div class="caption">
        <div clas="caption-content">
          <div class="user-name">
            <%= link_to post.user.user_name,
profile_path(post.user.user_name)%>
          </div>
          <%= post.caption %>
        </div>
        <div class="comments"  id="comments_<%= post.id %>">
          <!-- the if block code below is there in partial of comments but currently its creating problem if time use it-->
          <%if post.comments.any?%>
            <div class="paginator" id="comments-paginator<%=post.id%>">
              <%unless post.comments.count <=4 %>
                <%= link_to "view all  #{post.comments.count} comments",post_comments_path(post),remote:true,class:'more-comments',data:{post_id: "#{post.id}",type:"html"} %>
              <%end%>
              <%= render post.comments.last(4), post: post %>
            </div>
          <%end%>
        </div>
      </div>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <%= link_to '', "#{like_unlike post}", remote: true,id: "like_#{post.id}",:style=>'color:red',class: "glyphicon #{liked_post post}" %>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f|%>
          <%= f.text_field :content,placeholder:'Add a comment...', class:"comment_content",id: "comment_content_#{post.id}"%>
        <%end%>
      </div>
    </div>
  </div>

<!-- .posts-wrapper.row
-@posts.each do |post|
.post
.post-head
.name
Ben Walker
.image.center-block
=link_to (image_tag post.image.url(:medium), class:'img-
responsive'), post_path(post)
%p.caption
=post.caption -->

app/views/posts/_post_dashboard.html.erb
<div id="posts">
<%= render 'posts' %>
</div>
<div class="text-center" id="paginator">
<%= link_to_next_page @posts, 'LOAD MORE', remote: true, id:'load_more' %>
</div>

app/views/posts/_post_dashboard.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote:true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
<%= render 'post', post: post%>
<%end%>

app/views/posts/browse.html.erb
<%= render 'post_dashboard', posts: @posts %>

app/views/posts/edit.html.erb
<!-- <div class="text-center">
<%= image_tag @post.image.url(:medium) %>
</div> -->
<%= render 'form'%>
<div class="text-center">
<%= link_to "Delete Post", post_path(@post), method: :delete,
data: { confirm: "Are you sure you want to delete this post?" }%> |
<%= link_to "cancel", posts_path%>
</div>

app/views/posts/index.html.erb
<%= render 'post_dashboard', posts: @posts %>


<!-- .posts-wrapper.row
-@posts.each do |post|
.post
.post-head
.name
Ben Walker
.image.center-block
=link_to (image_tag post.image.url(:medium), class:'img-
responsive'), post_path(post)
%p.caption
=post.caption -->

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%=escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote:true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#like_<%= @post.id %>").prop("href", "/posts/<%= @post.id %>/unlike");
$("#likes_<%= @post.id %>").html("<%= j (render partial:'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.erb
<%if notice %>
       <p class="alert alert-success alert-dismissable" style="text-align: center;"><%= notice %>
       <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
       </p>
       <%end%>
        <%if alert%>
       <p class="alert alert-danger fade-in" style="text-align: center;background: rgba(255,0,0,0.29);"><%= alert %>
         <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
       </p>
       <%end%>
       <br> 
<%= render 'form'%>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>

<% if @post.user.id == current_user.id %>
<div class="text-center">
<%= link_to "Cancel", posts_path(@post) %> |
<%= link_to "Edit Post", edit_post_path(@post) %>
</div>
<%else%>
<div class="text-center">
<%= link_to "Cancel", posts_path(@post) %>
</div>
<%end%>

app/views/posts/unlike.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
$("#like_<%= @post.id %>").prop("href", "/posts/<%= @post.id %>/like");
$("#likes_<%= @post.id %>").html("<%= j (render partial:'posts/likes', locals: { post: @post} ) %>");