config/routes.rb
Rails.application.routes.draw do
post ':user_name/follow_user', to: 'relationships#follow_user',
as: :follow_user
post ':user_name/unfollow_user', to:
'relationships#unfollow_user', as: :unfollow_user


  # get 'notifications/link_through'
  get 'notifications/:id/link_through', to:'notifications#link_through',as: :link_through

  get 'notifications', to: 'notifications#index'

  get 'profiles/show'
  get 'browse', to: 'posts#browse', as: :browse_posts


  # devise_for :users
  devise_for :users, :controllers => { registrations:
'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :posts

resources :posts do
resources :comments
member do
get 'like'
get 'unlike'
end
end


  root 'posts#index'
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as:
  :update_profile



end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
<div class="navbar-container">
<div class="navbar-brand"><%= link_to "Photon", root_path%></div>
<div class="navbar-header"><br><br><br><br><br>
<!-- <button type="button" class="navbar-toggle collapsed">{"data-target" => "#bs-</button>
navbar-collapse-1", "data-toggle" => "collapse", type: "button"} -->
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1"></button>
<span class="sr-only">Toggle Navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>


<div id="bs-navbar-collapse-1" class="collapse navbar-collapse"> </div>
</div>
<!--   <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %> -->

        <nav>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li>
          <%= render 'notifications/notificiation_dropdown'%></li>
          <li><%= link_to "Browse Posts", browse_posts_path %></li>

 

          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path,:method => :delete %>
          <%else%>
            <li><%= link_to "Login",new_user_session_path %></li>
            <li><%= link_to "Register",new_user_registration_path %></li>
            <%end%>
          </ul>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photon</title>
 
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<%= render 'layouts/navbar'%>

     
      
 <div class="container">
<% flash.each do |name, msg| %>
<% content_tag :div, msg, class: [:alert, alert_for(name)]%>
<%end%>
</div>  
<!--         <%if notice %>
       <p class="alert alert-success alert-dismissable" style="text-align: center;"><%= notice %>
       <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
       </p>
       <%end%>
        <%if alert%>
       <p class="alert alert-danger fade-in" style="text-align: center;background: rgba(255,0,0,0.29);"><%= alert %>
         <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
       </p>
       <%end%>
       <br> -->

    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
   <!--<title>Alpha</title>-->
  <% if content_for?(:head)%>
  <%=content_for(:head)%>
  <%else%>
  <title>ThePhoton</title>
  <%end%>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="home" style='background-image: url("<%=image_path("login1.jpg")%>");'>

<%= yield %>

<br><br>
</body>
</html>